# Generated by Django 4.2.9 on 2024-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_rename_sale_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
