# Generated by Django 4.2.9 on 2024-02-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_post_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.carmodel'),
        ),
    ]
