# Generated by Django 4.2.9 on 2024-02-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_remove_post_car_make_post_production_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make', 'name']},
        ),
    ]
