# Generated by Django 4.2.9 on 2024-02-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_alter_carmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make__name', 'name']},
        ),
    ]
